[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sql-insight"
version = "0.1.0"
description = "A Python package for SQL query analysis and insights"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "sqlglot>=27.0"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
sqlinsight = "sqlinsight.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]